export enum Configuration {
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_USER = 'DB_USER',
  DB_NAME = 'DB_NAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_PORT = 'DB_PORT',
  TOKEN_SECRET = 'TOKEN_SECRET',
  RECAPTCHA_TOKEN_SECRET = 'RECAPTCHA_TOKEN_SECRET',
  ADMIN_ROLE = 'ADMIN_ROLE',
  USER_ROLE = 'USER_ROLE',
}
